version: '2'

services:

  app-data:
    container_name: m2d_app_data
    #build: vendor/cois-io/m2d-nginx
    image: coisio/m2d-nginx
    volumes:
      - .:/www
    command: /bin/true

  nginx:
    container_name: m2d_nginx
    #build: vendor/cois-io/m2d-nginx
    image: coisio/m2d-nginx
    volumes_from:
      - app-data
    networks:
      - backend
    depends_on:
      - php-fpm

  php-fpm:
    container_name: m2d_php_fpm
    #build: vendor/cois-io/m2d-php-fpm
    image: coisio/m2d-php-fpm
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes_from:
      - app-data
    networks:
      - backend
      - frontend
    depends_on:
      - redis-cache

  db-data:
    container_name: m2d_db_data
    image: percona:5.7
    volumes:
      - /var/lib/mysql
    command: /bin/true

  db:
    container_name: m2d_percona_db
    image: percona:5.7
    ports:
      - "3306:3306"
    depends_on:
      - db-data
      - elastic # force it to load last
    volumes_from:
      - db-data
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=magento
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    networks:
      - backend
      - frontend

  elastic-data:
    container_name: m2d_elastic_data
    #build: vendor/cois-io/m2d-elasticsearch
    image: cois-io/m2d-elasticsearch
    volumes:
      - /usr/share/elasticsearch/data
    command: /bin/true

  elastic:
    container_name: m2d_elasticsearch
    #build: vendor/cois-io/m2d-elasticsearch
    image: cois-io/m2d-elasticsearch
    volumes_from:
      - elastic-data
    networks:
      - backend

  varnish:
    container_name: m2d_varnish
    #build: vendor/cois-io/m2d-varnish
    image: coisio/m2d-varnish
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    depends_on:
      - nginx

  redis-cache:
    container_name: m2d_redis_cache
    image: redis
    networks:
      - backend

networks:
  backend:
  frontend:
